# Generated by Django 5.0.4 on 2024-06-05 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_userbookstatus_remove_book_file_userbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooks',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Site.userbookstatus'),
        ),
    ]
