# Generated by Django 5.0.4 on 2024-06-06 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_alter_userbooks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, upload_to='Book_file/'),
        ),
        migrations.AlterField(
            model_name='userbooks',
            name='status',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='Site.userbookstatus'),
        ),
    ]
