# Generated by Django 5.0.4 on 2024-06-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_book_book_file_alter_userbooks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, upload_to='books/'),
        ),
    ]
