# Generated by Django 5.0.4 on 2024-06-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_alter_book_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='Site.book'),
        ),
    ]
