# Generated by Django 5.0.4 on 2024-06-14 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0010_alter_book_description_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
